services:
  app:
    image: python:3.11
    container_name: python_app_monthly
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: >
      sh -c "pip install -r requirements.txt && tail -f /dev/null"